name: Windows

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*:*'

jobs:
  windows:
    name: >-
      ${{ matrix.ruby }}  windows-latest
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ mswin, mingw, 2.7, 2.6, 2.5, 2.4, 2.3 ]
    steps:
      - name: repo checkout
        uses: actions/checkout@v2

      - name: load ruby, update gcc, install openssl
        uses: MSP-Greg/actions-ruby@mswin
        with:
          ruby-version: ${{ matrix.ruby }}
          base: update
          mingw: openssl

      - name: depends
        run:  rake install_dependencies

      - name: compile
        shell: cmd
        env:
          RVERS: ${{ matrix.ruby }}
        run:  |
          if "%RVERS%" == "mswin" (
            call "%VCVARS%"
            rake compile -- --with-openssl-dir=C:/openssl-win --enable-debug
          ) else (
            if "%RVERS%" == "2.3" (
              rake compile -- --with-openssl-dir=C:/openssl-win --enable-debug
            ) else (
              rake compile -- --enable-debug
            )
          )

      - name: test
        run:  rake test TESTOPTS="-v --no-show-detail-immediately" OSSL_MDEBUG=1
        env:
          CI: true
